experiment_name: exp_convnext_base_clean_lr1e4_fold1
data_root: ..
train_csv: data/cv_splits/train_fold1.csv
val_csv: data/cv_splits/val_fold1.csv
test_csv: ../test_df.csv
train_images_dir: ../train_images_full_clean/train_images_full_clean
val_images_dir: ../train_images_full_clean/train_images_full_clean
test_images_dir: ../test_images/test_images
num_classes: 20
min_ratio: 0.0
model_name: convnext_base
pretrained: true
dropout: 0.3
img_size: 224
batch_size: 8
num_epochs: 12
lr: 0.0001
weight_decay: 0.0001
label_smoothing: 0.05
use_weighted_loss: false
preload: true
warmup_epochs: 2
early_stopping_patience: 4
seed: 42
output_dir: outputs/exp_convnext_base_clean_lr1e4_fold1
